---
title: 'Eye in a Disk: eyeIntegration human pan-eye and body transcriptome database
  version 1.0'
author: "David McGaughey"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: word_document
---

To the editor,

Dozens of research groups have deposited hundreds of human eye tissue RNA-seq transcriptomes in publicly available databases. To maximize the value of these datasets, we have built the "Eye in a Disk" (EiaD) dataset which contains all available non-perturbed eye tissues and the Gene Tissue Expression (GTEx) project human body tissues processed in a consistent and reproducible manner. To best serve this huge dataset, we have re-built the eyeIntegration web app (https://eyeIntegration.nei.nih.gov) to efficiently access the data and provide power interactive visualizations of gene expression across several tissue types within the human eye and across the entire human body. 

In a demonstration of the value of this large, uniformly processed dataset, we show both that 3D retina organoids and fetal tissue retina have highly similar transcriptomes. Since organoids do not yet fully mature, we also carefully studied gene expression differences between these two types and pinpoint how homeobox and protocadherin developmental processes are differentially expressed between the organoids and tissue. These processses may have relevance in retinal ganglion activity and the maturation of the organoids. 

The EiaD dataset and the eyeIntegration web app is freely available to download and deploy on local computers. As of January 2019, this resource has been used by researchers across 285 cities and 40 countries. The improvements we have made to this project in creating the reproducible databases and the matched web app will allow for continuous improvements in sample and feature additions over time. 

Sincerely,
David McGaughey Ph.D, Bioinformatics Group, OGVFB, NEI


