---
title: Test
author: |
  | $^1$OGVFB NEI NIH
  | David M McGaughey 1^[Corresponding author: mcgaugheyd@mail.nih.gov] $^1$, John M Bryan $^1$
abstract: |
  eyeIntegration is an series of open databases with an extensive transcriptomic database containing over 30 GTEx human body tissues as well as major components of the eye: retina, RPE, RPE-choroid, and cornea. eyeIntegration also holds two WGCNA networks for retina and RPE-choroid. Web application.
bibliography: Unified Gene Expression.bib
csl: genome-biology.csl
output:
  bookdown::pdf_document2:
  toc: yes
  word_document: default
fig_caption: yes
always_allow_html: yes
header-includes:
    - \usepackage{setspace}
    - \doublespacing
    - \usepackage{lineno}
    - \linenumbers
---


```{r Setup..., message=FALSE, warning=FALSE, include=FALSE}
#knitr::opts_chunk$set(fig.pos = 'p') # Places figures on their own pages
knitr::opts_chunk$set(out.width = '100%', dpi=300)

# I usually load my libraries up front to keep things organized
library(bookdown)
#library(knitr)
#library(kableExtra)
library(tidyverse)
library(citr)
```

# Introduction

```{r, fig.cap=paste('Density of num'), echo=F}
library(tidyverse)
rand <- sample(1:100, 100, replace=F)
rand %>% density() %>% plot()
```
# Materials and Methods

Cell | Number
----- | -----
RPE | 200
Fibroblast | 30


## Single Cell RNA-Seq Data
[@macoskoHighlyParallelGenomewide2015]

# Results

# Conclusions
